# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['posted']},
        ),
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='instagram.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='pic',
            field=models.ImageField(default=12, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='picture',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
