# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 07:01
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20180721_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pic',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
    ]
